name: nightly-master

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - 'master/Dockerfile'
      - 'master/alpine/Dockerfile'

env:
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - type: ""
            suffix: ""
          - type: "-alpine"
            suffix: "/alpine"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login into Docker Hub
        uses: docker/login-action@v3
        with:
          username: bitcoin
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: master${{ matrix.variant.suffix }}
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name == 'schedule' }}
          tags: bitcoin/bitcoin:master${{ matrix.variant.type }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ github.event.repository.updated_at }}
            VCS_REF=${{ github.sha }}
